//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_reports
    {
        public int ID { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double TotalPrice { get; set; }
        public double AmountPaid { get; set; }
        public Nullable<double> Change { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
